version: "3.9"

services:
  sql_temp:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: otus_calendar_test
      POSTGRES_USER: otus_calendar_user
      POSTGRES_PASSWORD: otus_calendar_password
  migration:
    build:
      context: ..
      dockerfile: ./docker/DockerfileMigration
    volumes:
      - ../:/calendar
    depends_on:
      - sql_temp
    command: /go/bin/goose postgres "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"  up
  mq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - migration
    environment:
      RABBITMQ_DEFAULT_USER: otus
      RABBITMQ_DEFAULT_PASS: pass
  calendar:
    build:
      context: ..
      dockerfile: ./docker/DockerfileCalendar
    volumes:
      - ../:/calendar
    ports:
      - "8018:8018"
      - "8019:8019"
    depends_on:
      - migration
      - mq
    command: /calendar/bin/calendar --config=/calendar/config/config_test.env
  scheduler:
    build:
      context: ..
      dockerfile: ./docker/DockerfileScheduler
    volumes:
      - ../:/calendar
    depends_on:
      - migration
      - mq
    command: /calendar/bin/scheduler --config=/calendar/config/config_test.env
  sender:
    build:
      context: ..
      dockerfile: ./docker/DockerfileSender
    volumes:
      - ../:/calendar
    depends_on:
      - migration
      - mq
    command: /calendar/bin/sender --config=/calendar/config/config_test.env
  integr:
    build:
      context: ..
      dockerfile: ./docker/DockerfileIntegr
    volumes:
      - ../:/calendar
    depends_on:
      - migration
      - mq
volumes:
  postgres:
    driver: local
networks:
  default:
    name: calendar_network
